/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado del servicio y de la regla
         * @description Dice si la regla de capacidad está cargada, si Garmin está disponible y con
         *     qué versiones corre. Si algo falla al desplegar, lo delata en un vistazo.
         */
        get: operations["meta_salud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/historial/archivos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Procesar archivos .FIT del historial
         * @description Procesa los .FIT y devuelve el historial en tramos de 100 m, sin guardarlo.
         *
         *     Si el historial no cabe en una petición, se sube por tandas y el navegador
         *     junta los tramos. El `.TCX` se rechaza con un 422 que lo explica: no hay
         *     lector en el proyecto.
         */
        post: operations["historial_subir_archivos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/historial/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Horas, sesiones y capacidad de un historial procesado
         * @description Lo que se le enseña al corredor en el paso 1: cuántas horas tiene, en cuántas
         *     sesiones, y —si se indica la distancia— qué le puede ofrecer la regla.
         */
        post: operations["historial_resumir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/historial/garmin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Arrancar la descarga del historial desde Garmin Connect
         * @description Arranca la descarga y devuelve el identificador para seguirla.
         *
         *     Devuelve 202 y no espera: reunir el historial lleva minutos, según las horas
         *     pedidas, por la pausa obligatoria contra el límite de peticiones de Garmin.
         *     El progreso se consulta en `GET /historial/garmin/{tarea_id}`.
         *
         *     Requiere `confirmado=true`: nunca se dispara sola. Lo descargado se parsea en
         *     memoria; no se guarda ningún archivo en el servidor.
         */
        post: operations["historial_descargar_de_garmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/historial/garmin/{tarea_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar el progreso de una descarga
         * @description Cuántas actividades y horas lleva, y el historial en tramos al terminar.
         */
        get: operations["historial_progreso_de_garmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/historial/garmin/{tarea_id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancelar una descarga en curso
         * @description Para la descarga y descarta lo que llevara bajado.
         *
         *     Responde en cuanto marca la tarea, sin esperar al hilo: cancelar tiene que
         *     sentirse inmediato. Lo ya reunido no se guarda — para quedarse con menos
         *     horas esta el selector, que para eso ofrece 50, 100 o 135.
         */
        post: operations["historial_cancelar_descarga_de_garmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capacidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qué modelo asigna la regla para unas horas y una distancia
         * @description Devuelve el modelo asignado y, si la respuesta es ritmo constante, el motivo real.
         *
         *     El motivo importa: para una carrera corta, "te faltan horas" sería falso. En
         *     el régimen corto ni con todo el historial medido se personaliza, así que el
         *     factor limitante es la distancia. Ver `regimen_fiable`.
         */
        get: operations["capacidad_capacidad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/objetivo/opciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Las cuatro opciones del selector
         * @description Para que la interfaz no escriba a mano ni las etiquetas ni los factores.
         */
        get: operations["objetivo_listar_opciones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/objetivo/sugerencia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sugerir un tiempo objetivo a partir del historial
         * @description Extrapola el mejor esfuerzo reciente del corredor con Riegel.
         *
         *     Si no hay ninguna sesión de al menos 5 km, `tiempo_objetivo_h` viene en null
         *     y `motivo` lo explica: entonces el tiempo lo teclea el usuario. El campo
         *     `editable` es siempre verdadero.
         */
        post: operations["objetivo_sugerencia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estrategia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calcular la estrategia de ritmo para una ruta
         * @description Entrena el modelo de este corredor y calcula su estrategia para la ruta.
         *
         *     El historial va como archivo y no como campo de formulario porque un
         *     historial largo pasa de 1 MB, que es el tope de un campo de texto en el
         *     multipart de Starlette.
         *
         *     El `km_objetivo` con el que se consulta la regla **sale de la propia ruta**,
         *     no de lo que diga el usuario: es la distancia que va a correr de verdad.
         */
        post: operations["estrategia_calcular_estrategia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exportar/garmin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subir el entrenamiento a la cuenta de Garmin
         * @description Sube el entrenamiento. Requiere confirmación explícita en cada llamada.
         *
         *     El JSON de Garmin se vuelve a construir aquí a partir de los pasos, en vez de
         *     aceptar el que mande el cliente: así el `conditionTypeId` lo pone siempre el
         *     servidor. La respuesta incluye lo que Garmin interpretó de cada paso. Si
         *     `todos_por_distancia` saliera falso, los pasos estarían esperando el botón de
         *     vuelta en vez de avanzar solos: es exactamente el bug que produjo usar
         *     `conditionTypeId = 1` en lugar del 3.
         */
        post: operations["exportar_subir_a_garmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/garmin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión en Garmin Connect
         * @description Primer paso. Si la cuenta tiene MFA, la respuesta trae `requiere_mfa=true`.
         *
         *     La contraseña se usa para autenticar y se borra del cliente en cuanto el
         *     login termina. No se llama a `login(tokenstore)`, que es lo que guardaría un
         *     token en disco.
         */
        post: operations["garmin_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/garmin/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Completar el login con el código de verificación
         * @description Segundo paso, solo si el login devolvió `requiere_mfa=true`.
         */
        post: operations["garmin_mfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/garmin/sesion/{sesion_garmin_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cerrar la sesión de Garmin
         * @description Suelta el cliente autenticado antes de que caduque solo.
         *
         *     Conviene llamarlo al terminar: cuanto menos viva una sesión contra una
         *     cuenta real, mejor.
         */
        delete: operations["garmin_cerrar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sesion/olvidar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Soltar de memoria la sesión y la descarga de Garmin
         * @description Suelta todo lo que el cliente diga tener.
         *
         *     Idempotente a propósito: borrar algo que ya caducó, o que nunca existió, no
         *     es un error. Lo que importa es que al volver no quede nada, no informar de
         *     qué había. Por eso tampoco valida los identificadores: si no existen, no
         *     pasa nada.
         */
        post: operations["sesion_olvidar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArchivoFit */
        ArchivoFit: {
            /** Nombre Archivo */
            nombre_archivo: string;
            /**
             * Contenido Base64
             * @description El .FIT del entrenamiento (unos cientos de bytes), listo para descargar.
             */
            contenido_base64: string;
        };
        /** Body_estrategia_calcular_estrategia */
        Body_estrategia_calcular_estrategia: {
            /**
             * Gpx
             * @description Ruta objetivo en .GPX
             */
            gpx: string;
            /**
             * Historial
             * @description El historial procesado (los `tramos` de `POST /historial/archivos`), en JSON
             */
            historial: string;
            /**
             * Tiempo Objetivo H
             * @description Tiempo objetivo en horas
             */
            tiempo_objetivo_h: number;
            /**
             * Temperatura C
             * @default 18
             */
            temperatura_c: number;
        };
        /** Body_historial_subir_archivos */
        Body_historial_subir_archivos: {
            /**
             * Archivos
             * @description Uno o más archivos .FIT
             */
            archivos: string[];
        };
        /**
         * Capacidad
         * @description Lo que la regla de capacidad responde para unas horas y una distancia.
         *
         *     `motivo` solo viene cuando `personalizada` es falso:
         *
         *     - `historial_insuficiente` — todavía no llega al primer presupuesto medido.
         *     - `sin_evidencia_en_esta_franja` — esta franja no superó al ritmo constante,
         *       pero otras con más horas sí lo hacen.
         *     - `distancia_sin_evidencia` — ni con todo el historial medido personaliza
         *       este régimen. El límite es la distancia, no las horas.
         */
        Capacidad: {
            /** Horas */
            horas: number;
            /** Km Objetivo */
            km_objetivo: number;
            /** Regimen */
            regimen: string;
            /** Modelo */
            modelo: string;
            /** Habilidad Esperada */
            habilidad_esperada: number;
            /** Nivel Capacidad */
            nivel_capacidad: number;
            /** Personalizada */
            personalizada: boolean;
            /** Motivo */
            motivo?: ("historial_insuficiente" | "sin_evidencia_en_esta_franja" | "distancia_sin_evidencia") | null;
            siguiente_franja?: components["schemas"]["SiguienteFranja"] | null;
            /**
             * Regimen Fiable
             * @description Si la franja con más horas de este régimen personaliza. Cuando es falso, acumular historial no desbloquea nada aquí.
             */
            regimen_fiable: boolean;
            /**
             * Regimen Monotono
             * @description Si el nivel de modelo crece con las horas sin bajar nunca. En maratón es falso: más horas no siempre significan mejor modelo.
             */
            regimen_monotono: boolean;
            /**
             * Validado En Km
             * @description Rango de distancias con el que se validó este régimen.
             */
            validado_en_km: number[];
            /**
             * Distancia Extrapolada
             * @description La distancia objetivo cae fuera de lo validado (p. ej. una media maratón).
             */
            distancia_extrapolada: boolean;
            /** Franjas */
            franjas: components["schemas"]["Franja"][];
        };
        /** DetalleError */
        DetalleError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** EntradaEstrategia */
        EntradaEstrategia: {
            /** Tiempo Objetivo H */
            tiempo_objetivo_h: number;
            /** Temperatura C */
            temperatura_c: number;
        };
        /** Entrenamiento */
        Entrenamiento: {
            /** Nombre */
            nombre: string;
            /** Pasos */
            pasos: components["schemas"]["PasoEntrenamiento"][];
            /** Segundos Estimados */
            segundos_estimados: number;
            /**
             * Payload Garmin
             * @description El mismo entrenamiento en el esquema JSON de Garmin Connect.
             */
            payload_garmin: {
                [key: string]: unknown;
            };
            /** Aviso */
            aviso: string;
        };
        /**
         * EntrenamientoParaSubir
         * @description Lo que devolvió `POST /estrategia` en `entrenamiento`, de vuelta para subirlo.
         */
        EntrenamientoParaSubir: {
            /** Nombre */
            nombre: string;
            /** Segundos Estimados */
            segundos_estimados: number;
            /** Pasos */
            pasos: components["schemas"]["PasoEntrenamiento"][];
        };
        /**
         * EstadoDescarga
         * @description El progreso de una descarga de Garmin.
         *
         *     Se consulta cada pocos segundos mientras dura. El porcentaje es real: se
         *     calcula sobre las horas pedidas, que se conocen antes de empezar.
         */
        EstadoDescarga: {
            /** Tarea Id */
            tarea_id: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "en_curso" | "terminada" | "fallida" | "cancelada";
            /**
             * Actividades
             * @description Actividades descargadas hasta ahora.
             */
            actividades: number;
            /** Horas */
            horas: number;
            /** Objetivo Horas */
            objetivo_horas: number;
            /** Porcentaje */
            porcentaje: number;
            /** Segundos */
            segundos: number;
            /** @description Solo cuando el estado es «terminada». */
            resultado?: components["schemas"]["HistorialProcesado"] | null;
            /** Error */
            error?: string | null;
            /** Codigo Error */
            codigo_error?: string | null;
        };
        /** Estrategia */
        Estrategia: {
            ruta: components["schemas"]["InfoRuta"];
            entrada: components["schemas"]["EntradaEstrategia"];
            capacidad: components["schemas"]["Capacidad"];
            indicadores: components["schemas"]["Indicadores"];
            /** Tabla Km */
            tabla_km: components["schemas"]["FilaKm"][];
            /** Altimetria */
            altimetria: components["schemas"]["PuntoAltimetria"][];
            /** Reparto Zonas */
            reparto_zonas: {
                [key: string]: number;
            };
            /** @description Los pasos para el reloj, ya compilados: no hay que pedirlos aparte. */
            entrenamiento: components["schemas"]["Entrenamiento"];
            fit: components["schemas"]["ArchivoFit"];
        };
        /** FilaKm */
        FilaKm: {
            /** Km */
            km: number;
            /**
             * Ritmo Objetivo
             * @description min/km
             */
            ritmo_objetivo: number;
            /**
             * Fc Objetivo
             * @description bpm
             */
            fc_objetivo: number;
            /**
             * Pendiente
             * @description %
             */
            pendiente: number;
            /**
             * Elevacion
             * @description msnm
             */
            elevacion: number;
            /** Zona */
            zona: string;
            /** Tiempo Min */
            tiempo_min: number;
            /** Tiempo Acum Min */
            tiempo_acum_min: number;
        };
        /** Franja */
        Franja: {
            /** Desde Horas */
            desde_horas: number;
            /** Sesiones */
            sesiones: number;
            /** Modelo */
            modelo: string;
            /** Habilidad */
            habilidad: number;
            /** Nivel */
            nivel: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistorialProcesado */
        HistorialProcesado: {
            tramos: components["schemas"]["TramosHistorial"];
            /**
             * Control Calidad
             * @description Cuántos archivos se descartaron y por qué motivo.
             */
            control_calidad: {
                [key: string]: number;
            };
        };
        /** Indicadores */
        Indicadores: {
            /** Tiempo Estimado H */
            tiempo_estimado_h: number;
            /** Desnivel Positivo M */
            desnivel_positivo_m: number;
            /** Pendiente Maxima Pct */
            pendiente_maxima_pct: number;
            /** Pct Exigencia Alta */
            pct_exigencia_alta: number;
            /** Fc Objetivo Media */
            fc_objetivo_media: number;
        };
        /** InfoReglas */
        InfoReglas: {
            /** Cargadas */
            cargadas: boolean;
            /** Carpeta */
            carpeta: string;
            /**
             * Motivo
             * @description Por qué no cargó, si no cargó
             */
            motivo?: string | null;
            /**
             * Version Artefacto
             * @description Versión del artefacto del que se extrajo la regla
             */
            version_artefacto?: string | null;
            /** Creado */
            creado?: string | null;
            /** Regimenes */
            regimenes?: string[];
        };
        /** InfoRuta */
        InfoRuta: {
            /** Nombre */
            nombre: string;
            /** Km Totales */
            km_totales: number;
            /** Tramos */
            tramos: number;
        };
        /** OpcionObjetivo */
        OpcionObjetivo: {
            /**
             * Clave
             * @enum {string}
             */
            clave: "maximizar rendimiento" | "mejor marca" | "terminar sin fatiga" | "ritmo conservador";
            /** Etiqueta */
            etiqueta: string;
            /** Descripcion */
            descripcion: string;
            /** Factor */
            factor: number;
            /** Por Defecto */
            por_defecto: boolean;
        };
        /** PasoEntrenamiento */
        PasoEntrenamiento: {
            /** Km Inicio */
            km_inicio: number;
            /** Km Fin */
            km_fin: number;
            /** Km */
            km: number;
            /** Zona */
            zona: string;
            /** Ritmo Min */
            ritmo_min: number;
            /** Ritmo Max */
            ritmo_max: number;
            /** Fc Min */
            fc_min: number;
            /** Fc Max */
            fc_max: number;
            /** Minutos */
            minutos: number;
            /** Nombre */
            nombre: string;
            /** Notas */
            notas: string;
        };
        /** PeticionDescargaGarmin */
        PeticionDescargaGarmin: {
            /** Sesion Garmin Id */
            sesion_garmin_id: string;
            /**
             * Objetivo Horas
             * @description Horas brutas de actividades a descargar; el control de calidad descarta algunas.
             * @default 135
             */
            objetivo_horas: number;
            /**
             * Confirmado
             * @description Tiene que ser true. La descarga nunca se dispara sola.
             * @default false
             */
            confirmado: boolean;
        };
        /**
         * PeticionLoginGarmin
         * @description Credenciales de una cuenta real de Garmin Connect.
         *
         *     No se guardan en ningún sitio: ni en disco, ni en base de datos, ni en los
         *     logs. La sesión vive en memoria y caduca a los 15 minutos.
         */
        PeticionLoginGarmin: {
            /** Correo */
            correo: string;
            /**
             * Contrasena
             * Format: password
             */
            contrasena: string;
        };
        /** PeticionMfaGarmin */
        PeticionMfaGarmin: {
            /** Sesion Garmin Id */
            sesion_garmin_id: string;
            /**
             * Codigo
             * Format: password
             */
            codigo: string;
        };
        /**
         * PeticionOlvidar
         * @description Lo que el cliente dice tener vivo en el servidor.
         *
         *     Solo puede ser de Garmin: el historial y la estrategia nunca se guardan allí.
         *     Todos opcionales: se borra lo que haya, sin informar de qué seguía vivo.
         */
        PeticionOlvidar: {
            /** Sesion Garmin Id */
            sesion_garmin_id?: string | null;
            /**
             * Tarea Id
             * @description Una descarga de Garmin, que retiene el historial reunido
             */
            tarea_id?: string | null;
        };
        /** PeticionResumen */
        PeticionResumen: {
            tramos: components["schemas"]["TramosHistorial"];
            /**
             * Km Objetivo
             * @description Si se indica, se consulta la regla de capacidad
             */
            km_objetivo?: number | null;
        };
        /** PeticionSubidaGarmin */
        PeticionSubidaGarmin: {
            /** Sesion Garmin Id */
            sesion_garmin_id: string;
            entrenamiento: components["schemas"]["EntrenamientoParaSubir"];
            /**
             * Confirmado
             * @description Tiene que ser true. La subida nunca se dispara sola.
             * @default false
             */
            confirmado: boolean;
        };
        /** PeticionSugerencia */
        PeticionSugerencia: {
            tramos: components["schemas"]["TramosHistorial"];
            /** Km Objetivo */
            km_objetivo: number;
            /**
             * Objetivo
             * @default terminar sin fatiga
             * @enum {string}
             */
            objetivo: "maximizar rendimiento" | "mejor marca" | "terminar sin fatiga" | "ritmo conservador";
        };
        /** PuntoAltimetria */
        PuntoAltimetria: {
            /** Dist Km */
            dist_km: number;
            /** Elevacion */
            elevacion: number;
        };
        /** ReferenciaEsfuerzo */
        ReferenciaEsfuerzo: {
            /** Fecha */
            fecha: string;
            /** Km */
            km: number;
            /** Minutos */
            minutos: number;
            /** Ritmo Min Km */
            ritmo_min_km: number;
        };
        /** RespuestaError */
        RespuestaError: {
            error: components["schemas"]["DetalleError"];
        };
        /** ResultadoOlvidar */
        ResultadoOlvidar: {
            /**
             * Borrados
             * @description Qué se soltó de memoria, para poder verlo en los tests.
             */
            borrados?: string[];
        };
        /** ResultadoSubida */
        ResultadoSubida: {
            /** Workout Id */
            workout_id: number | string | null;
            /** Nombre */
            nombre: string | null;
            /** Pasos Segun Garmin */
            pasos_segun_garmin: {
                [key: string]: unknown;
            }[];
            /**
             * Todos Por Distancia
             * @description Si algún paso saliera como lap.button, el reloj esperaría el botón de vuelta en vez de avanzar por distancia.
             */
            todos_por_distancia: boolean;
            /** Aviso */
            aviso: string;
        };
        /** ResumenHistorial */
        ResumenHistorial: {
            /** Horas */
            horas: number;
            /** Sesiones */
            sesiones: number;
            /** Km Totales */
            km_totales: number;
            /** Desde */
            desde: string;
            /** Hasta */
            hasta: string;
            /** @description Solo si se indicó km_objetivo. */
            capacidad?: components["schemas"]["Capacidad"] | null;
        };
        /** Salud */
        Salud: {
            /**
             * Estado
             * @enum {string}
             */
            estado: "ok" | "degradado";
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Entorno */
            entorno: string;
            reglas: components["schemas"]["InfoReglas"];
            /**
             * Garmin Habilitado
             * @description Si la conexión con Garmin está disponible en este despliegue. Necesita estado en el servidor; `STAMINA_GARMIN_HABILITADO=False` la apaga.
             */
            garmin_habilitado: boolean;
            /**
             * Dependencias
             * @description Versiones de pandas y scikit-learn.
             */
            dependencias: {
                [key: string]: string;
            };
            /**
             * Sesiones Activas
             * @description Sesiones de Garmin y descargas vivas. Nada más se guarda en el servidor.
             */
            sesiones_activas: {
                [key: string]: number;
            };
        };
        /** SesionGarmin */
        SesionGarmin: {
            /** Sesion Garmin Id */
            sesion_garmin_id: string;
            /** Autenticada */
            autenticada: boolean;
            /** Requiere Mfa */
            requiere_mfa: boolean;
            /**
             * Correo
             * @description Enmascarado a propósito
             */
            correo: string;
            /** Caduca En Segundos */
            caduca_en_segundos: number;
            /** Aviso */
            aviso: string;
        };
        /** SiguienteFranja */
        SiguienteFranja: {
            /** Desde Horas */
            desde_horas: number;
            /** Modelo */
            modelo: string;
            /** Habilidad */
            habilidad: number;
            /** Horas Faltantes */
            horas_faltantes: number;
        };
        /**
         * Sugerencia
         * @description Un tiempo objetivo sugerido a partir del historial del propio corredor.
         *
         *     **No es una predicción del modelo.** Es una extrapolación de Riegel sobre su
         *     mejor esfuerzo reciente, y por eso `editable` es siempre verdadero: es un
         *     punto de partida que el corredor puede cambiar.
         */
        Sugerencia: {
            /**
             * Objetivo
             * @enum {string}
             */
            objetivo: "maximizar rendimiento" | "mejor marca" | "terminar sin fatiga" | "ritmo conservador";
            /** Etiqueta */
            etiqueta: string;
            /** Km Objetivo */
            km_objetivo: number;
            /** Tiempo Objetivo H */
            tiempo_objetivo_h: number | null;
            /** Ritmo Medio Min Km */
            ritmo_medio_min_km?: number | null;
            /** Editable */
            editable: boolean;
            /**
             * Motivo
             * @description Por qué no se pudo sugerir nada
             */
            motivo?: string | null;
            /** Metodo */
            metodo?: string | null;
            referencia?: components["schemas"]["ReferenciaEsfuerzo"] | null;
            /** Factor */
            factor: number;
        };
        /**
         * TramosHistorial
         * @description El historial procesado: una fila por cada 100 m de cada sesión, en columnas.
         *
         *     **Lo guarda el navegador, no el servidor.** Sale de `POST /historial/archivos`
         *     y vuelve en cada petición que lo necesita. No lleva coordenadas: solo lo que
         *     el pipeline usa para aprender cómo corre esta persona.
         */
        TramosHistorial: {
            /**
             * Split
             * @description Número de tramo de 100 m dentro de la sesión
             */
            split: number[];
            /**
             * V
             * @description Velocidad media, m/s
             */
            v: number[];
            /**
             * Fc
             * @description Frecuencia cardíaca media, bpm
             */
            fc: number[];
            /** Cadencia */
            cadencia: number[];
            /**
             * Elev
             * @description Altitud al final del tramo, m
             */
            elev: number[];
            /**
             * Temperatura
             * @description °C; null si el reloj no la grabó
             */
            temperatura: (number | null)[];
            /**
             * T Fin
             * @description Segundos desde el inicio de la sesión
             */
            t_fin: number[];
            /** N Registros */
            n_registros: number[];
            /**
             * Actividad
             * @description Identificador de la sesión (el nombre del .FIT)
             */
            actividad: string[];
            /**
             * Fecha
             * @description AAAA-MM-DD
             */
            fecha: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    meta_salud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Salud"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    historial_subir_archivos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_historial_subir_archivos"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorialProcesado"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    historial_resumir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionResumen"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumenHistorial"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    historial_descargar_de_garmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionDescargaGarmin"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoDescarga"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    historial_progreso_de_garmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tarea_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoDescarga"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    historial_cancelar_descarga_de_garmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tarea_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoDescarga"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    capacidad_capacidad: {
        parameters: {
            query: {
                /** @description Horas acumuladas de carrera */
                horas: number;
                /** @description Distancia de la carrera objetivo */
                km_objetivo: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capacidad"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    objetivo_listar_opciones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpcionObjetivo"][];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    objetivo_sugerencia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionSugerencia"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sugerencia"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    estrategia_calcular_estrategia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_estrategia_calcular_estrategia"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Estrategia"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    exportar_subir_a_garmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionSubidaGarmin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoSubida"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    garmin_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionLoginGarmin"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionGarmin"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    garmin_mfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionMfaGarmin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionGarmin"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    garmin_cerrar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesion_garmin_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
    sesion_olvidar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeticionOlvidar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoOlvidar"];
                };
            };
            /** @description Garmin rechazó las credenciales */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no está disponible en este despliegue */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description El recurso no existe o ya caducó */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Falta confirmación explícita */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no deja pasar ahora */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Error no previsto */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description Garmin no responde o responde mal */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
            /** @description La regla de capacidad no está cargada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaError"];
                };
            };
        };
    };
}
